// Regenerate src/generated/ from the committed schema documents.
//
// The schema documents in ../schema are the contract authority, produced by
// the Ellipsis backend (its test suite fails when they drift from the server
// models); this script derives the TypeScript types from them so the SDK's
// types are never hand-written. CI regenerates and diffs, so a schema change
// that forgets `pnpm gen` fails the build.
//
//   frames.schema.json    -> src/generated/frames.ts    (WS frame + wire types)
//   openapi.v1.json       -> src/generated/openapi.ts   (REST paths + components)
//   lifecycle.schema.json -> src/generated/lifecycle.ts (lifecycle record payloads)

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from 'json-schema-to-typescript';
import openapiTS, { astToString } from 'openapi-typescript';
import prettier from 'prettier';

const here = dirname(fileURLToPath(import.meta.url));
const schemaDir = join(here, '../../schema');
const outDir = join(here, '../src/generated');
mkdirSync(outDir, { recursive: true });

const banner = (source) =>
  `/* eslint-disable */\n// Generated by scripts/gen-types.mjs from ${source} — do not edit by hand.\n`;

// Mirror .prettierrc so `pnpm format:check` accepts the generated output.
const prettierOptions = {
  parser: 'typescript',
  singleQuote: true,
  trailingComma: 'es5',
};

// The JSON Schema leaves objects open (the protocol tolerates additive server
// fields), but an open schema compiles to `[k: string]: unknown` index
// signatures that poison property access. Closing the objects here changes
// only the generated TYPES, not the contract: clients ignore unknown fields
// either way.
function closeObjects(node) {
  if (Array.isArray(node)) {
    node.forEach(closeObjects);
    return;
  }
  if (node === null || typeof node !== 'object') return;
  if (node.type === 'object' && !('additionalProperties' in node)) {
    // A bare `{"type": "object"}` (a record's native `payload`) genuinely IS
    // an open bag — keep it open; only close objects with declared properties.
    if (node.properties) node.additionalProperties = false;
  }
  for (const value of Object.values(node)) closeObjects(value);
}

// Pydantic titles every property subschema ("Id", "Created At", …), and
// json-schema-to-typescript hoists any titled subschema into its own exported
// alias (Id1, CreatedAt1, Number, …) — pure noise. Strip titles everywhere
// below a definition's top level so only the model names become types.
function stripNestedTitles(node, isTop) {
  if (Array.isArray(node)) {
    node.forEach((child) => stripNestedTitles(child, false));
    return;
  }
  if (node === null || typeof node !== 'object') return;
  if (!isTop) delete node.title;
  for (const [key, value] of Object.entries(node)) {
    if (key === '$defs') {
      for (const def of Object.values(value)) stripNestedTitles(def, true);
    } else {
      stripNestedTitles(value, false);
    }
  }
}

// frames.schema.json -> frames.ts
const framesSchema = JSON.parse(
  readFileSync(join(schemaDir, 'frames.schema.json'), 'utf8')
);
closeObjects(framesSchema);
stripNestedTitles(framesSchema, true);
const framesTs = await compile(framesSchema, 'SessionStreamFrame', {
  bannerComment: banner('schema/frames.schema.json'),
  additionalProperties: false,
});
writeFileSync(
  join(outDir, 'frames.ts'),
  await prettier.format(framesTs, prettierOptions)
);
console.log('Wrote src/generated/frames.ts');

// lifecycle.schema.json -> lifecycle.ts
// Root = LifecyclePayloads, a record_type -> payload map, so renderers write
// LifecyclePayloads['sandbox_log'] and stay pinned to the server models.
const lifecycleSchema = JSON.parse(
  readFileSync(join(schemaDir, 'lifecycle.schema.json'), 'utf8')
);
closeObjects(lifecycleSchema);
stripNestedTitles(lifecycleSchema, true);
const lifecycleTs = await compile(lifecycleSchema, 'LifecyclePayloads', {
  bannerComment: banner('schema/lifecycle.schema.json'),
  additionalProperties: false,
});
writeFileSync(
  join(outDir, 'lifecycle.ts'),
  await prettier.format(lifecycleTs, prettierOptions)
);
console.log('Wrote src/generated/lifecycle.ts');

// openapi.v1.json -> openapi.ts
const openapiDoc = JSON.parse(
  readFileSync(join(schemaDir, 'openapi.v1.json'), 'utf8')
);
const ast = await openapiTS(openapiDoc);
const openapiTs = await prettier.format(
  banner('schema/openapi.v1.json') + astToString(ast),
  prettierOptions
);
writeFileSync(join(outDir, 'openapi.ts'), openapiTs);
console.log('Wrote src/generated/openapi.ts');
