"""Generated by ellipsis.pyscripts.sdk.generate_sdks — do not edit by hand.

The collection-stream frame models, derived from the committed
`packages/sdk/schema/collection_frames.schema.json`. The resources frames carry are the
same wire models the REST client returns (`models.Session`, ...), so REST
and stream can never disagree.
"""

from typing import Literal, Union

from . import models
from .models import EllipsisModel


class AgentListStreamMessage(EllipsisModel):
    agents: list[models.Agent]
    type: Literal["agents"]


class CollectionStreamHeartbeat(EllipsisModel):
    type: Literal["heartbeat"]


class SandboxSnapshotFrame(EllipsisModel):
    sandbox: models.VMExecutionResponse
    type: Literal["snapshot"]


class SandboxUpdateFrame(EllipsisModel):
    sandbox: models.VMExecutionResponse
    type: Literal["sandbox"]


class SessionListStreamMessage(EllipsisModel):
    session: models.Session
    type: Literal["session"]


StreamFrame = Union[
    AgentListStreamMessage,
    CollectionStreamHeartbeat,
    SandboxSnapshotFrame,
    SandboxUpdateFrame,
    SessionListStreamMessage,
]
"""One server->client frame. Unknown frame types must be ignored
(additive server changes are not a protocol break)."""


__all__ = [
    "AgentListStreamMessage",
    "CollectionStreamHeartbeat",
    "SandboxSnapshotFrame",
    "SandboxUpdateFrame",
    "SessionListStreamMessage",
    "StreamFrame",
]
