"""Generated by ellipsis.pyscripts.sdk.generate_sdks — do not edit by hand.

The session-stream frame models (protocol v3), derived from the committed
`packages/sdk/schema/frames.schema.json`. The resources frames carry are the
same wire models the REST client returns (`models.Session`, ...), so REST
and stream can never disagree.
"""

from datetime import datetime
from typing import Literal, Union

from pydantic import Field

from . import models
from .models import EllipsisModel


class DeltaFrame(EllipsisModel):
    """Fire-and-forget partial assistant output for the current response.
    Carries no sequence number and is never resumable; superseded by the
    committed record.
    """

    agent_turn_id: Union[str, None] = Field(
        description="Identifier of the turn the delta belongs to, if known."
    )
    kind: str = Field(
        description="What the partial text is. Known values: text ('thinking' reserved). Open vocabulary: ignore deltas with unknown kinds."
    )
    output_tokens: Union[int, None] = Field(
        description="Output tokens generated so far for the current response."
    )
    text: Union[str, None] = Field(description="The partial output text.")
    type: Literal["delta"]


class DoneFrame(EllipsisModel):
    """Terminal marker: the conversation is over, after the final session
    frame carried the end state. Followed by a normal close (1000).
    """

    type: Literal["done"]


class ErrorFrame(EllipsisModel):
    """Terminal error marker, sent before the server closes with code 1011."""

    message: str = Field(description="A human-readable error message.")
    type: Literal["error"]


class HeartbeatFrame(EllipsisModel):
    """A keepalive sent after a period of idleness; doubles as the dead-socket
    probe. Clients should treat roughly twice the heartbeat interval of
    silence as a dead connection.
    """

    ts: datetime = Field(description="Server time when the heartbeat was sent.")
    type: Literal["heartbeat"]


class RecordsAppendFrame(EllipsisModel):
    """Cursored append-only delivery of session records, ordered by feed_seq,
    from all sources. Every record in the frame advances the resume cursor —
    including ones a client renders as nothing.
    """

    records: list[
        Union[
            models.ClaudeSessionRecord,
            models.CodexSessionRecord,
            models.LifecycleSessionRecord,
        ]
    ] = Field(description="New session records, ordered by feed_seq.")
    type: Literal["records_append"]


class SessionFrame(EllipsisModel):
    """A last-writer-wins snapshot of the session — the only way status,
    state, and cost updates arrive. Resent whole on any field change.
    """

    session: models.Session = Field(description="The session's current state.")
    type: Literal["session"]


class SnapshotFrame(EllipsisModel):
    """The first frame after the stream connects: the session plus its open
    inbox. Records always arrive separately via records_append frames.
    """

    earliest_feed_seq: Union[int, None] = Field(
        description="The retention head: the lowest feed_seq still stored for this session, or null when it has no stored records. A client resuming from after_seq < earliest_feed_seq - 1 knows history is truncated."
    )
    messages: list[models.SessionMessage] = Field(
        description="The session's open (pending) inbox messages."
    )
    protocol: int = Field(
        description="Echoes the protocol version the server is serving."
    )
    session: models.Session = Field(description="The session's current state.")
    type: Literal["snapshot"]


StreamFrame = Union[
    DeltaFrame,
    DoneFrame,
    ErrorFrame,
    HeartbeatFrame,
    RecordsAppendFrame,
    SessionFrame,
    SnapshotFrame,
]
"""One server->client frame. Unknown frame types must be ignored
(additive server changes are not a protocol break)."""


__all__ = [
    "DeltaFrame",
    "DoneFrame",
    "ErrorFrame",
    "HeartbeatFrame",
    "RecordsAppendFrame",
    "SessionFrame",
    "SnapshotFrame",
    "StreamFrame",
]
