"""Generated by ellipsis.pyscripts.sdk.generate_sdks — do not edit by hand.

The lifecycle record payloads, derived from the committed
`packages/sdk/schema/lifecycle.schema.json`. A session record whose
`record_format` is `ellipsis_lifecycle@1` carries one of these as its
`payload`; `LIFECYCLE_PAYLOADS` maps the record's `record_type` to the model
that parses it.

The contract is additive-only: clients MUST ignore unknown record types and
unknown payload fields, and MUST render unknown phase/step/status values
generically.
"""

from typing import Any, Union

from pydantic import Field

from .models import EllipsisModel


class MessageDeliveredPayload(EllipsisModel):
    """message_delivered — a turn consumed the message."""

    message_id: str
    turn_id: str


class MessageReceivedPayload(EllipsisModel):
    """message_received — a message landed in the session inbox. Puts "what
    arrived, from whom, when" in the downloadable log; the session_messages
    row is the internal delivery projection.
    """

    author: Union[str, None] = None
    body: str
    closes_session: bool = False
    message_id: str
    sender_attribution_id: Union[str, None] = None
    sender_attribution_type: Union[str, None] = None


class MessageRequeuedPayload(EllipsisModel):
    """message_requeued — an errored turn returned the message to the inbox
    (at-least-once delivery; the next wake redelivers).
    """

    message_id: str
    turn_id: str


class OutboxCollectedPayload(EllipsisModel):
    """outbox_collected — the platform read a code_review session's
    /ellipsis/outbox/* at finalize (CODE_REVIEW_v3.md §3). Carries both raw
    and parsed so the feed alone tells the whole delivery story; the
    code_review_outbox table is the queryable projection of this record.
    """

    findings: list[dict[str, Any]] = Field(default_factory=list)
    parse_errors: list[dict[str, Any]] = Field(default_factory=list)
    parser_version: str
    raw: dict[str, str] = Field(default_factory=dict)


class SandboxOutputPayload(EllipsisModel):
    """sandbox_output — one chunk of provisioning/lifecycle-script output.
    Many fire per execution; `chunk` rides the idempotency key. These records
    ARE the durable copy (archived into the session log's S3 segments), under
    a high per-session cap + truncation marker.
    """

    chunk: int
    lines: list[str]
    phase: str
    step: Union[str, None] = None
    stream: str = "stdout"


class SandboxPhasePayload(EllipsisModel):
    """sandbox_phase — one transition of the provisioning state machine, so
    clients can narrate 'found a cached image' / 'cloning' / 'snapshotting'
    live and locate failures. Phases are an OPEN vocabulary (SandboxPhase has
    the known values); `detail` carries phase-specific extras additively
    (e.g. {"cache_tier": "incremental"} on image completion).
    """

    detail: Union[dict[str, Any], None] = None
    duration_ms: Union[int, None] = None
    phase: str
    status: str
    step: Union[str, None] = None


class SandboxReadyPayload(EllipsisModel):
    """sandbox_ready — the box is up and the harness is about to launch: the
    summary anchor closing the provisioning story. cache_tier/phase_timings
    duplicate the sandboxes-row columns purely for rendering convenience — the
    row is the authority (§2).
    """

    cache_tier: Union[str, None] = None
    phase_timings: dict[str, float] = Field(default_factory=dict)
    repositories: list[str]


class SandboxStartingPayload(EllipsisModel):
    """sandbox_starting — provisioning begins for this execution."""

    repositories: list[str]


class SessionCancelledPayload(EllipsisModel):
    """session_cancelled — a preflight gate cancelled the session before any
    sandbox existed. Session-scoped (no execution).
    """

    reason: str


class SessionClosedPayload(EllipsisModel):
    """session_closed — the conversation terminalized (closing event's final
    turn, or an ephemeral session's terminal).
    """


class SessionIdlePayload(EllipsisModel):
    """session_idle — the warm loop ended and the durable conversation is
    parked; the next message wakes it.
    """


class SessionResumedPayload(EllipsisModel):
    """session_resumed — a wake mounted the teardown snapshots and --resumed
    the transcript. Its ABSENCE after a wake is the degraded-wake signal.
    """

    wake_index: int


class SessionRetryingPayload(EllipsisModel):
    """session_retrying — a transient infra failure before the agent acted
    handed the session back for another attempt (bounded).
    """

    attempt: int
    reason: str


class SessionScheduledPayload(EllipsisModel):
    """session_scheduled — the session row exists and is queued for a worker.
    The one session-scoped record emitted at creation (no execution yet).
    """

    config_commit_sha: Union[str, None] = None
    config_name: Union[str, None] = None
    source: str


class SessionStartingPayload(EllipsisModel):
    """session_starting — a worker claimed the session and preflight passed.
    Emitted on EVERY claim; clients render wake_index > 0 as a wake.
    """

    attempt: int
    wake_index: int


class TurnCompletedPayload(EllipsisModel):
    """turn_completed — the turn's result event closed it."""

    duration_ms: Union[int, None] = None
    turn_id: str
    turn_index: int


class TurnFailedPayload(EllipsisModel):
    """turn_failed — the turn terminalized without completing (its consumed
    messages requeue).
    """

    turn_id: str
    turn_index: int


class TurnStartedPayload(EllipsisModel):
    """turn_started — a message-exchange began."""

    turn_id: str
    turn_index: int


LifecyclePayload = Union[
    MessageDeliveredPayload,
    MessageReceivedPayload,
    MessageRequeuedPayload,
    OutboxCollectedPayload,
    SandboxOutputPayload,
    SandboxPhasePayload,
    SandboxReadyPayload,
    SandboxStartingPayload,
    SessionCancelledPayload,
    SessionClosedPayload,
    SessionIdlePayload,
    SessionResumedPayload,
    SessionRetryingPayload,
    SessionScheduledPayload,
    SessionStartingPayload,
    TurnCompletedPayload,
    TurnFailedPayload,
    TurnStartedPayload,
]
"""One `ellipsis_lifecycle@1` record payload. Which member a record
carries is keyed by its `record_type` — see LIFECYCLE_PAYLOADS."""


LIFECYCLE_PAYLOADS: dict[str, type[LifecyclePayload]] = {
    "message_delivered": MessageDeliveredPayload,
    "message_received": MessageReceivedPayload,
    "message_requeued": MessageRequeuedPayload,
    "outbox_collected": OutboxCollectedPayload,
    "sandbox_output": SandboxOutputPayload,
    "sandbox_phase": SandboxPhasePayload,
    "sandbox_ready": SandboxReadyPayload,
    "sandbox_starting": SandboxStartingPayload,
    "session_cancelled": SessionCancelledPayload,
    "session_closed": SessionClosedPayload,
    "session_idle": SessionIdlePayload,
    "session_resumed": SessionResumedPayload,
    "session_retrying": SessionRetryingPayload,
    "session_scheduled": SessionScheduledPayload,
    "session_starting": SessionStartingPayload,
    "turn_completed": TurnCompletedPayload,
    "turn_failed": TurnFailedPayload,
    "turn_started": TurnStartedPayload,
}
"""`record_type` -> the model that parses that record's `payload`.
Record types are an OPEN vocabulary: a type absent here is a newer
server event, to be ignored rather than treated as an error."""


__all__ = [
    "MessageDeliveredPayload",
    "MessageReceivedPayload",
    "MessageRequeuedPayload",
    "OutboxCollectedPayload",
    "SandboxOutputPayload",
    "SandboxPhasePayload",
    "SandboxReadyPayload",
    "SandboxStartingPayload",
    "SessionCancelledPayload",
    "SessionClosedPayload",
    "SessionIdlePayload",
    "SessionResumedPayload",
    "SessionRetryingPayload",
    "SessionScheduledPayload",
    "SessionStartingPayload",
    "TurnCompletedPayload",
    "TurnFailedPayload",
    "TurnStartedPayload",
    "LIFECYCLE_PAYLOADS",
    "LifecyclePayload",
]
