"""Generated by ellipsis.pyscripts.sdk.generate_sdks — do not edit by hand.

The lifecycle record payloads, derived from the committed
`packages/sdk/schema/lifecycle.schema.json`. A session record whose
`record_format` is `ellipsis_lifecycle@1` carries one of these as its
`payload`; `LIFECYCLE_PAYLOADS` maps the record's `record_type` to the model
that parses it.

The contract is additive-only: clients MUST ignore unknown record types and
unknown payload fields, and MUST render unknown phase/step/status values
generically.
"""

from typing import Any, Union

from pydantic import Field

from .models import EllipsisModel


class EnvironmentOutputPayload(EllipsisModel):
    """environment_output: one chunk of output from preparing the environment,
    including the customer's own hooks. Many fire per turn; `chunk` orders them
    within a step.
    """

    chunk: int
    lines: list[str]
    phase: str
    step: Union[str, None] = None
    stream: str = "stdout"


class EnvironmentPhasePayload(EllipsisModel):
    """environment_phase: one transition of environment preparation, so clients
    can narrate progress live and locate failures. Phases are an OPEN
    vocabulary; `detail` carries phase-specific extras additively.
    """

    detail: Union[dict[str, Any], None] = None
    duration_ms: Union[int, None] = None
    phase: str
    status: str
    step: Union[str, None] = None


class EnvironmentReadyPayload(EllipsisModel):
    """environment_ready: the environment is prepared and the agent is about
    to start.
    """

    duration_ms: Union[int, None] = None
    repositories: list[str]


class MessageDeliveredPayload(EllipsisModel):
    """message_delivered: the agent started on the message."""

    message_id: str
    turn_id: str


class MessageReceivedPayload(EllipsisModel):
    """message_received: a message landed in the session inbox and its turn was
    created. `turn_id` is the turn that will answer it.
    """

    author: Union[str, None] = None
    body: str
    closes_session: bool = False
    message_id: str
    sender_attribution_id: Union[str, None] = None
    sender_attribution_type: Union[str, None] = None
    turn_id: Union[str, None] = None


class MessageRequeuedPayload(EllipsisModel):
    """message_requeued: a turn was interrupted before answering, so the
    message goes back to the inbox with a new pending turn.
    """

    message_id: str
    requeued_turn_id: Union[str, None] = None
    turn_id: str


class OutboxCollectedPayload(EllipsisModel):
    """outbox_collected: the platform read a code_review session's
    /ellipsis/outbox/* when its turn ended. Carries both raw and parsed so
    the feed alone tells the whole delivery story; the code_review_outbox
    table is the queryable projection of this record.
    """

    findings: list[dict[str, Any]] = Field(default_factory=list)
    parse_errors: list[dict[str, Any]] = Field(default_factory=list)
    parser_version: str
    raw: dict[str, str] = Field(default_factory=dict)


class SessionClosedPayload(EllipsisModel):
    """session_closed: the conversation closed permanently."""


class TurnEndedPayload(EllipsisModel):
    """turn_ended: the turn reached its final status. `status`, `reason`, and
    `detail` match the turn on the session object.
    """

    detail: Union[str, None] = None
    duration_ms: Union[int, None] = None
    reason: Union[str, None] = None
    status: str
    turn_id: str
    turn_index: int


class TurnStartedPayload(EllipsisModel):
    """turn_started: the agent started on the turn's message."""

    turn_id: str
    turn_index: int


LifecyclePayload = Union[
    EnvironmentOutputPayload,
    EnvironmentPhasePayload,
    EnvironmentReadyPayload,
    MessageDeliveredPayload,
    MessageReceivedPayload,
    MessageRequeuedPayload,
    OutboxCollectedPayload,
    SessionClosedPayload,
    TurnEndedPayload,
    TurnStartedPayload,
]
"""One `ellipsis_lifecycle@1` record payload. Which member a record
carries is keyed by its `record_type` — see LIFECYCLE_PAYLOADS."""


LIFECYCLE_PAYLOADS: dict[str, type[LifecyclePayload]] = {
    "environment_output": EnvironmentOutputPayload,
    "environment_phase": EnvironmentPhasePayload,
    "environment_ready": EnvironmentReadyPayload,
    "message_delivered": MessageDeliveredPayload,
    "message_received": MessageReceivedPayload,
    "message_requeued": MessageRequeuedPayload,
    "outbox_collected": OutboxCollectedPayload,
    "session_closed": SessionClosedPayload,
    "turn_ended": TurnEndedPayload,
    "turn_started": TurnStartedPayload,
}
"""`record_type` -> the model that parses that record's `payload`.
Record types are an OPEN vocabulary: a type absent here is a newer
server event, to be ignored rather than treated as an error."""


__all__ = [
    "EnvironmentOutputPayload",
    "EnvironmentPhasePayload",
    "EnvironmentReadyPayload",
    "MessageDeliveredPayload",
    "MessageReceivedPayload",
    "MessageRequeuedPayload",
    "OutboxCollectedPayload",
    "SessionClosedPayload",
    "TurnEndedPayload",
    "TurnStartedPayload",
    "LIFECYCLE_PAYLOADS",
    "LifecyclePayload",
]
