// Generated by ellipsis.pyscripts.sdk.generate_sdks — do not edit by hand.
//
// The client surface: one method per /v1 operation, generated from the
// committed OpenAPI spec + the operation map. Model types come from the
// openapi-typescript output (`pnpm gen`); this module only arranges them
// into a namespaced client over the hand-written transport.

import type { components } from '../generated/openapi';
import { Page } from './pagination';
import { SessionHandle } from './sessionHandle';
import { buildBody, buildQuery, Transport } from './transport';
import type { TransportOptions } from './transport';

type S = components['schemas'];

const enc = encodeURIComponent;


class EllipsisAlerts {
  constructor(private readonly transport: Transport) {
  }

  /**
   * Dismiss Alert
   *
   * Dismiss an open alert and return it.
   *
   * 409 when the alert is not open; 404 when it doesn't exist.
   */
  async dismiss(alert_id: string): Promise<S['AlertResponse']> {
    const path = `/v1/alerts/${enc(alert_id)}/dismiss`;
    return await this.transport.request<S['AlertResponse']>('POST', path);
  }

  /**
   * Get Alert
   *
   * Return one alert by id.
   *
   * 404 if it doesn't exist or belongs to another organization.
   */
  async get(alert_id: string): Promise<S['AlertResponse']> {
    const path = `/v1/alerts/${enc(alert_id)}`;
    return await this.transport.request<S['AlertResponse']>('GET', path);
  }

  /**
   * List Alerts
   *
   * List budget alerts for the organization, newest first.
   *
   * Optionally filtered by status and source.
   *
   * Available to all credential types, so an agent can check "is
   * this org near budget?" mid-task.
   */
  async list(options: { status?: S['AlertStatus'] | null; source?: S['AlertSource'] | null; limit?: number; cursor?: string | null } = {}): Promise<Page<S['Alert'], S['AlertsListResponse']>> {
    const path = '/v1/alerts';
    const query = buildQuery({ status: options.status, source: options.source, limit: options.limit, cursor: options.cursor });
    const response = await this.transport.request<S['AlertsListResponse']>('GET', path, { query });
    return new Page(response, 'alerts', (cursor) =>
      this.list({ ...options, cursor })
    );
  }
}

class EllipsisAnalytics {
  constructor(private readonly transport: Transport) {
  }

  /**
   * Get Analytics Metrics
   *
   * Return PR and review analytics metrics.
   *
   * The same data as the analytics dashboard.
   *
   * Windowing: pass explicit start/end, or days (default: the last
   * 30 days). account_type in all|user|bot scopes the authors (bot =
   * the apps/agents). Available to all credential types: the
   * responses expose the organization's own GitHub PR/review activity,
   * no secrets.
   */
  async metrics(options: { days?: number | null; start?: string | null; end?: string | null; repo?: (string)[] | null; author?: (string)[] | null; account_type?: string; status?: (string)[] | null } = {}): Promise<S['GetAnalyticsMetricsResponse']> {
    const path = '/v1/analytics/metrics';
    const query = buildQuery({ days: options.days, start: options.start, end: options.end, repo: options.repo, author: options.author, account_type: options.account_type, status: options.status });
    return await this.transport.request<S['GetAnalyticsMetricsResponse']>('GET', path, { query });
  }

  /**
   * Get Analytics Pull Requests
   *
   * Return pull-request analytics.
   *
   * Windowing: pass explicit start/end, or days (default: the last
   * 30 days). account_type in all|user|bot scopes the authors.
   */
  async pullRequests(options: { days?: number | null; start?: string | null; end?: string | null; repo?: (string)[] | null; author?: (string)[] | null; account_type?: string; status?: (string)[] | null } = {}): Promise<S['GetAnalyticsPullRequestsResponse']> {
    const path = '/v1/analytics/pull-requests';
    const query = buildQuery({ days: options.days, start: options.start, end: options.end, repo: options.repo, author: options.author, account_type: options.account_type, status: options.status });
    return await this.transport.request<S['GetAnalyticsPullRequestsResponse']>('GET', path, { query });
  }

  /**
   * Get Analytics Reviews
   *
   * Return code-review analytics.
   *
   * account_type scopes reviewers (bot|user|all) — e.g. "what apps
   * review the most PRs?" is the reviewer facets here with
   * account_type=bot. Windowing: pass explicit start/end, or days
   * (default: the last 30 days).
   */
  async reviews(options: { days?: number | null; start?: string | null; end?: string | null; repo?: (string)[] | null; author?: (string)[] | null; account_type?: string; review_state?: (string)[] | null } = {}): Promise<S['GetAnalyticsReviewsResponse']> {
    const path = '/v1/analytics/reviews';
    const query = buildQuery({ days: options.days, start: options.start, end: options.end, repo: options.repo, author: options.author, account_type: options.account_type, review_state: options.review_state });
    return await this.transport.request<S['GetAnalyticsReviewsResponse']>('GET', path, { query });
  }
}

class EllipsisAuthCli {
  constructor(private readonly transport: Transport) {
  }

  /**
   * Cli Auth Poll
   *
   * Poll a device-code auth flow for its token.
   *
   * Unauthenticated; the device code identifies the flow.
   */
  async poll(options: { device_code: string }): Promise<S['PollCliAuthResponse']> {
    const path = '/v1/auth/cli/poll';
    const body = buildBody({ device_code: options.device_code });
    return await this.transport.request<S['PollCliAuthResponse']>('POST', path, { body });
  }

  /**
   * Cli Auth Start
   *
   * Start a device-code auth flow for the CLI.
   *
   * Unauthenticated: the CLI has no credential yet — that's what
   * it's obtaining. The human authorizes out-of-band in the
   * dashboard.
   */
  async start(): Promise<S['StartCliAuthResponse']> {
    const path = '/v1/auth/cli/start';
    return await this.transport.request<S['StartCliAuthResponse']>('POST', path);
  }
}

class EllipsisAuth {
  readonly cli: EllipsisAuthCli;
  constructor(private readonly transport: Transport) {
    this.cli = new EllipsisAuthCli(transport);
  }
}

class EllipsisAutomations {
  constructor(private readonly transport: Transport) {
  }

  /**
   * Create Automation
   *
   * Create an automation, managed through the API: no file, live
   * immediately. To put its definition in a repository instead, create
   * it here and then POST /v1/automations/{automation_id}/link.
   *
   * 409 when another live automation already holds the name.
   */
  async create(options: { automation: S['AutomationConfig'] }): Promise<S['AutomationResponse']> {
    const path = '/v1/automations';
    const body = buildBody({ automation: options.automation });
    return await this.transport.request<S['AutomationResponse']>('POST', path, { body });
  }

  /**
   * Delete Automation
   *
   * Delete an automation, by id or by name.
   *
   * It stops running and its name is freed immediately; its past
   * sessions remain readable. Only for automations managed through
   * this API — delete the file to remove one defined by a repository.
   */
  async delete(automation_id: string): Promise<void> {
    const path = `/v1/automations/${enc(automation_id)}`;
    await this.transport.request<void>('DELETE', path);
  }

  /**
   * Get Automation
   *
   * Return one automation, by id or by name.
   */
  async get(automation_id: string): Promise<S['AutomationResponse']> {
    const path = `/v1/automations/${enc(automation_id)}`;
    return await this.transport.request<S['AutomationResponse']>('GET', path);
  }

  /**
   * Link Automation
   *
   * Move an automation into a repository, by id or by name.
   *
   * Opens a pull request adding its definition file. The automation
   * keeps running unchanged meanwhile; merging hands it over to the
   * file, after which the file is what changes it. Nothing happens
   * if the pull request is never merged.
   */
  async link(automation_id: string, options: { path?: string | null; repository: string }): Promise<S['LinkAutomationResponse']> {
    const path = `/v1/automations/${enc(automation_id)}/link`;
    const body = buildBody({ path: options.path, repository: options.repository });
    return await this.transport.request<S['LinkAutomationResponse']>('POST', path, { body });
  }

  /**
   * List Automations
   *
   * List automations.
   */
  async list(): Promise<S['AutomationsListResponse']> {
    const path = '/v1/automations';
    return await this.transport.request<S['AutomationsListResponse']>('GET', path);
  }

  /**
   * Get Automation Metrics
   *
   * Return an automation's session distribution and trailing spend,
   * by id or by name.
   *
   * `samples` carries one entry per finished session (duration, cost,
   * tokens) for distributions; `spend_windows` carries what the
   * automation's sessions cost over the last 1, 7, and 28 days against
   * its budget for each window.
   */
  async metrics(automation_id: string): Promise<S['AutomationMetricsResponse']> {
    const path = `/v1/automations/${enc(automation_id)}/metrics`;
    return await this.transport.request<S['AutomationMetricsResponse']>('GET', path);
  }

  /**
   * Start Automation Session
   *
   * Invoke an automation.
   *
   * Runs the automation exactly as defined — its persona, model,
   * environment, permissions, skills, and budget bind — and returns
   * the session it started. The body carries only what a caller may
   * supply: the typed `input` its schema demands, an optional tighter
   * `budget`, and `metadata`. For a different persona or environment,
   * start a raw session with POST /v1/sessions instead.
   */
  async run(automation_id: string, options: { budget?: number | null; input?: Record<string, unknown> | null; metadata?: Record<string, string> } = {}): Promise<S['SessionResponse']> {
    const path = `/v1/automations/${enc(automation_id)}/sessions`;
    const body = buildBody({ budget: options.budget, input: options.input, metadata: options.metadata });
    return await this.transport.request<S['SessionResponse']>('POST', path, { body });
  }

  /**
   * Unlink Automation
   *
   * Take over an automation from its file, by id or by name.
   *
   * The file stops governing it immediately and further changes go
   * through this API. The file is left in place, inert — delete it
   * whenever you like.
   */
  async unlink(automation_id: string): Promise<S['AutomationResponse']> {
    const path = `/v1/automations/${enc(automation_id)}/unlink`;
    return await this.transport.request<S['AutomationResponse']>('POST', path);
  }

  /**
   * Update Automation
   *
   * Replace an automation's definition, by id or by name.
   *
   * The whole definition is replaced, and the change is live at
   * once. Only for automations managed through this API: one defined
   * by a repository file is a 409, since the next push to that file
   * would revert the change — unlink it first to take ownership.
   */
  async update(automation_id: string, options: { automation: S['AutomationConfig'] }): Promise<S['AutomationResponse']> {
    const path = `/v1/automations/${enc(automation_id)}`;
    const body = buildBody({ automation: options.automation });
    return await this.transport.request<S['AutomationResponse']>('PUT', path, { body });
  }
}

class EllipsisEnvironments {
  constructor(private readonly transport: Transport) {
  }

  /**
   * Create Environment
   *
   * Create an environment, managed through the API: no file, live
   * immediately. To define it in a repository instead, commit a
   * `kind: environment` YAML under an agents directory.
   *
   * 409 when another live environment already holds the name.
   */
  async create(options: { environment: S['EnvironmentDocument'] }): Promise<S['EnvironmentResponse']> {
    const path = '/v1/environments';
    const body = buildBody({ environment: options.environment });
    return await this.transport.request<S['EnvironmentResponse']>('POST', path, { body });
  }

  /**
   * Delete Environment
   *
   * Delete an environment, by id or by name.
   *
   * Always succeeds, even while agents still reference it — their next
   * session start fails with a clear error naming the missing
   * environment. Past sessions remain readable. Only for environments
   * managed through this API — delete the file to remove one defined
   * by a repository.
   */
  async delete(environment_id: string): Promise<void> {
    const path = `/v1/environments/${enc(environment_id)}`;
    await this.transport.request<void>('DELETE', path);
  }

  /**
   * Get Environment
   *
   * Return one saved environment, by id or by name.
   */
  async get(environment_id: string): Promise<S['EnvironmentResponse']> {
    const path = `/v1/environments/${enc(environment_id)}`;
    return await this.transport.request<S['EnvironmentResponse']>('GET', path);
  }

  /**
   * List Environments
   *
   * List saved environments.
   */
  async list(): Promise<S['EnvironmentsListResponse']> {
    const path = '/v1/environments';
    return await this.transport.request<S['EnvironmentsListResponse']>('GET', path);
  }

  /**
   * Update Environment
   *
   * Replace an environment's definition, by id or by name.
   *
   * The whole definition is replaced, live at once — future sessions
   * resolve the new body; running sessions keep the one frozen at
   * their start. Only for environments managed through this API: one
   * defined by a repository file is a 409.
   */
  async update(environment_id: string, options: { environment: S['EnvironmentDocument'] }): Promise<S['EnvironmentResponse']> {
    const path = `/v1/environments/${enc(environment_id)}`;
    const body = buildBody({ environment: options.environment });
    return await this.transport.request<S['EnvironmentResponse']>('PUT', path, { body });
  }
}

class EllipsisFiles {
  constructor(private readonly transport: Transport) {
  }

  /**
   * Create File
   *
   * Upload a file that outlives the sandbox.
   *
   * v1: PNG images only, base64 in the JSON body, 10 MiB cap. The
   * primary caller is the in-sandbox `agent file upload` CLI (an
   * agent persisting a screenshot to link on a PR), but all
   * credential types work. Returns the org-membership-gated
   * dashboard URL so callers never hard-code URL shapes.
   */
  async create(options: { content_type: string; data_b64: string; filename: string }): Promise<S['CreateFileResponse']> {
    const path = '/v1/files';
    const body = buildBody({ content_type: options.content_type, data_b64: options.data_b64, filename: options.filename });
    return await this.transport.request<S['CreateFileResponse']>('POST', path, { body });
  }

  /**
   * Delete File
   *
   * Delete a file.
   *
   * A foreign, missing, or already-deleted id is an
   * indistinguishable 404, so ids can't be enumerated. Sandbox
   * tokens get a 403 (a sandbox token sits next to
   * potentially-untrusted code and must not be able to destroy the
   * account's files — uploading is fine, destruction is not); API
   * keys and user tokens may delete.
   */
  async delete(file_id: string): Promise<void> {
    const path = `/v1/files/${enc(file_id)}`;
    await this.transport.request<void>('DELETE', path);
  }

  /**
   * Get File
   *
   * Return one file's metadata and download link.
   *
   * Includes the gated dashboard URL and a short-lived presigned
   * `download_url`.
   *
   * To fetch the bytes locally, call this and then GET download_url
   * immediately — the JSON API never carries the file. The CLI's
   * `agent file get` wraps exactly that two-step.
   */
  async get(file_id: string): Promise<S['GetFileResponse']> {
    const path = `/v1/files/${enc(file_id)}`;
    return await this.transport.request<S['GetFileResponse']>('GET', path);
  }

  /**
   * List Files
   *
   * List uploaded files, newest first.
   *
   * Metadata only — download URLs are minted per explicit GET, not
   * per row. session_id scopes the list to one run's uploads.
   */
  async list(options: { session_id?: string | null; limit?: number; cursor?: string | null } = {}): Promise<Page<S['File'], S['FilesListResponse']>> {
    const path = '/v1/files';
    const query = buildQuery({ session_id: options.session_id, limit: options.limit, cursor: options.cursor });
    const response = await this.transport.request<S['FilesListResponse']>('GET', path, { query });
    return new Page(response, 'files', (cursor) =>
      this.list({ ...options, cursor })
    );
  }
}

class EllipsisIntegrationsGithub {
  constructor(private readonly transport: Transport) {
  }

  /**
   * List Github Members
   *
   * List the GitHub organization roster.
   *
   * (Or the account itself for a personal workspace) — the universe of author_id values for
   * /sessions.
   *
   * Members carry their linked Slack identity when a Slack-GitHub
   * link exists, and /slack/members carries the reverse link.
   */
  async members(): Promise<S['GithubMembersListResponse']> {
    const path = '/v1/integrations/github/members';
    return await this.transport.request<S['GithubMembersListResponse']>('GET', path);
  }

  /**
   * List Github Repositories
   *
   * List GitHub repositories connected to the installation.
   */
  async repos(): Promise<S['GithubRepositoriesListResponse']> {
    const path = '/v1/integrations/github/repos';
    return await this.transport.request<S['GithubRepositoriesListResponse']>('GET', path);
  }
}

class EllipsisIntegrationsLinear {
  constructor(private readonly transport: Transport) {
  }

  /**
   * List Linear Teams
   *
   * List the teams of the connected Linear workspace.
   */
  async teams(): Promise<S['LinearTeamsListResponse']> {
    const path = '/v1/integrations/linear/teams';
    return await this.transport.request<S['LinearTeamsListResponse']>('GET', path);
  }
}

class EllipsisIntegrationsSentry {
  constructor(private readonly transport: Transport) {
  }

  /**
   * List Sentry Organizations
   *
   * List the connected Sentry organizations.
   */
  async organizations(): Promise<S['SentryOrganizationsListResponse']> {
    const path = '/v1/integrations/sentry/organizations';
    return await this.transport.request<S['SentryOrganizationsListResponse']>('GET', path);
  }
}

class EllipsisIntegrationsSlack {
  constructor(private readonly transport: Transport) {
  }

  /**
   * List Slack Channels
   *
   * List the channels of the connected Slack workspace, fetched
   * live from the Slack API.
   */
  async channels(): Promise<S['SlackChannelsListResponse']> {
    const path = '/v1/integrations/slack/channels';
    return await this.transport.request<S['SlackChannelsListResponse']>('GET', path);
  }

  /**
   * List Slack Members
   *
   * List the members of the connected Slack workspace, fetched
   * live from the Slack API.
   */
  async members(): Promise<S['SlackMembersListResponse']> {
    const path = '/v1/integrations/slack/members';
    return await this.transport.request<S['SlackMembersListResponse']>('GET', path);
  }
}

class EllipsisIntegrations {
  readonly github: EllipsisIntegrationsGithub;
  readonly linear: EllipsisIntegrationsLinear;
  readonly sentry: EllipsisIntegrationsSentry;
  readonly slack: EllipsisIntegrationsSlack;
  constructor(private readonly transport: Transport) {
    this.github = new EllipsisIntegrationsGithub(transport);
    this.linear = new EllipsisIntegrationsLinear(transport);
    this.sentry = new EllipsisIntegrationsSentry(transport);
    this.slack = new EllipsisIntegrationsSlack(transport);
  }

  /**
   * List Integrations
   *
   * List connected integrations.
   *
   * A read-only view, so an agent authoring another agent's
   * config can learn which repositories, channels, teams, and
   * organizations it may name before POST /automations.
   *
   * Available to all credential types including sandbox tokens: the
   * responses never include OAuth tokens or any other secret.
   */
  async list(): Promise<S['GetIntegrationsResponse']> {
    const path = '/v1/integrations';
    return await this.transport.request<S['GetIntegrationsResponse']>('GET', path);
  }
}

class EllipsisMemories {
  constructor(private readonly transport: Transport) {
  }

  /**
   * Create Memory
   *
   * Save a memory for future agent sessions.
   *
   * Memories are durable lessons shared across the whole
   * organization — conventions, past decisions, known gotchas that an
   * agent cannot derive from the repository itself. One concise fact
   * per memory; the description is what a reader sees in the index.
   *
   * Creating never overwrites: a path that already exists is a 409, so
   * correcting an existing memory is an explicit edit.
   */
  async create(options: { content: string; description: string; path: string }): Promise<S['MemoryResponse']> {
    const path = '/v1/memories';
    const body = buildBody({ content: options.content, description: options.description, path: options.path });
    return await this.transport.request<S['MemoryResponse']>('POST', path, { body });
  }

  /**
   * Delete Memory
   *
   * Delete a memory that is no longer true.
   *
   * Available to every credential type, agents included — a wrong
   * memory is worse than a missing one. The deleted content is kept in
   * the memory's history for forensics, not for an undo API.
   */
  async delete(memory_id: string, options: { if_sha256?: string | null } = {}): Promise<void> {
    const path = `/v1/memories/${enc(memory_id)}`;
    const query = buildQuery({ if_sha256: options.if_sha256 });
    await this.transport.request<void>('DELETE', path, { query });
  }

  /**
   * Edit Memory
   *
   * Correct an existing memory in place.
   *
   * Pass description, content, or both. This never creates a memory (an
   * unknown id is a 404) and never moves one — the path is immutable, so
   * relocating a memory is a delete plus a create.
   *
   * Pass `if_sha256` (from a previous read) to make a concurrent write
   * a 409 instead of silently overwriting it.
   */
  async edit(memory_id: string, options: { content?: string | null; description?: string | null; if_sha256?: string | null } = {}): Promise<S['MemoryResponse']> {
    const path = `/v1/memories/${enc(memory_id)}`;
    const body = buildBody({ content: options.content, description: options.description, if_sha256: options.if_sha256 });
    return await this.transport.request<S['MemoryResponse']>('PUT', path, { body });
  }

  /**
   * Get Memory
   *
   * Read one memory's full content.
   *
   * The id comes from the index returned by listing memories.
   */
  async get(memory_id: string): Promise<S['MemoryResponse']> {
    const path = `/v1/memories/${enc(memory_id)}`;
    return await this.transport.request<S['MemoryResponse']>('GET', path);
  }

  /**
   * List Memories
   *
   * List the organization's memories as a readable index.
   *
   * Returns the memories rendered as a markdown index (one line per
   * memory, carrying its id, path, and description) plus the same
   * entries structured, each with every field except `content`. Read
   * the index, then fetch the ids whose content you want.
   */
  async list(options: { prefix?: string | null } = {}): Promise<S['MemoriesListResponse']> {
    const path = '/v1/memories';
    const query = buildQuery({ prefix: options.prefix });
    return await this.transport.request<S['MemoriesListResponse']>('GET', path, { query });
  }
}

class EllipsisModels {
  constructor(private readonly transport: Transport) {
  }

  /**
   * List Supported Models
   *
   * List selectable agent models.
   *
   * Most expensive first, with the platform default flagged.
   *
   * Reads the same registry as the dashboard's rate table, so a
   * client's model picker can never drift from what's offered.
   * Behind auth but not account-scoped — the selectable set is
   * global.
   */
  async list(): Promise<S['ModelsListResponse']> {
    const path = '/v1/models';
    return await this.transport.request<S['ModelsListResponse']>('GET', path);
  }
}

class EllipsisReviews {
  constructor(private readonly transport: Transport) {
  }

  /**
   * Create Review
   *
   * Run a code review on demand.
   *
   * Reviews an open pull request. Which pipeline runs is not a
   * parameter: it resolves from the repository's files exactly as
   * it does for a push, so an on-demand review never disagrees with
   * the automatic one.
   *
   * A review is one pipeline run over one commit range, with one
   * agent session per stage: `review.id` is the run id, and
   * `stages[].session_id` is where a client streams
   * (/sessions/{id}/stream on a stage session), since the review
   * itself is a pipeline rather than one process.
   */
  async create(options: { owner: string; post?: boolean; pull_request_number: number; repo: string; scope?: S['ReviewScope'] }): Promise<S['Review']> {
    const path = '/v1/reviews';
    const body = buildBody({ owner: options.owner, post: options.post, pull_request_number: options.pull_request_number, repo: options.repo, scope: options.scope });
    return await this.transport.request<S['Review']>('POST', path, { body });
  }

  /**
   * Get Review
   *
   * Return one review with findings and outcome.
   *
   * Includes its scope, the per-stage sessions, the parsed findings,
   * the finding counters, and the posting outcome.
   *
   * Findings only exist after a stage session finalizes — a running
   * review honestly reports [] / null, which is why a client
   * streams a stage session and then re-fetches the review.
   */
  async get(review_id: string): Promise<S['Review']> {
    const path = `/v1/reviews/${enc(review_id)}`;
    return await this.transport.request<S['Review']>('GET', path);
  }

  /**
   * List Reviews
   *
   * List code reviews, newest first.
   *
   * `findings` and `configuration` are omitted (counters only). Each
   * filter is a set: repeat `repository`, `pull_request_number`, or
   * `status` to match any of several values. `start` and `end` bound
   * the review's creation time.
   *
   * Webhook-created reviews appear here too, so this answers "show
   * me every review on this PR".
   */
  async list(options: { repository?: (string)[]; pull_request_number?: (number)[]; status?: (S['CodeReviewRunStatus'])[]; start?: string | null; end?: string | null; limit?: number; cursor?: string | null } = {}): Promise<Page<S['Review'], S['ReviewsListResponse']>> {
    const path = '/v1/reviews';
    const query = buildQuery({ repository: options.repository, pull_request_number: options.pull_request_number, status: options.status, start: options.start, end: options.end, limit: options.limit, cursor: options.cursor });
    const response = await this.transport.request<S['ReviewsListResponse']>('GET', path, { query });
    return new Page(response, 'reviews', (cursor) =>
      this.list({ ...options, cursor })
    );
  }
}

class EllipsisSecrets {
  constructor(private readonly transport: Transport) {
  }

  /**
   * Delete Secret
   *
   * Delete a secret by name.
   *
   * Refused for sandbox tokens; mutations require an API key or
   * user token.
   */
  async delete(name: string): Promise<void> {
    const path = `/v1/secrets/${enc(name)}`;
    await this.transport.request<void>('DELETE', path);
  }

  /**
   * List Secrets
   *
   * List secrets.
   *
   * Values are write-only: the response carries only names and
   * timestamps, never the stored value.
   */
  async list(): Promise<S['SecretsListResponse']> {
    const path = '/v1/secrets';
    return await this.transport.request<S['SecretsListResponse']>('GET', path);
  }

  /**
   * Set Secrets
   *
   * Upsert secrets.
   *
   * Returns only the secrets this call wrote, names and timestamps
   * only — values are write-only. Refused for sandbox tokens (held by
   * potentially-untrusted in-sandbox code); mutations require an
   * API key or user token.
   */
  async set(options: { secrets: (S['SecretInput'])[] }): Promise<S['SecretsListResponse']> {
    const path = '/v1/secrets';
    const body = buildBody({ secrets: options.secrets });
    return await this.transport.request<S['SecretsListResponse']>('PUT', path, { body });
  }
}

class EllipsisSessions {
  constructor(private readonly transport: Transport) {
  }

  /**
   * Get Agent Session Diff
   *
   * Return the session's uncommitted changes as a patch.
   *
   * One unified-diff section per changed file, captured from the
   * sandbox's working tree when the session ended. The per-file
   * counts ride on the session itself (`git.repos[].files`); this
   * is the text behind them. Empty when the tree was clean. A
   * sandbox token may read only its own session's diff.
   */
  async diff(session_id: string): Promise<S['SessionDiffResponse']> {
    const path = `/v1/sessions/${enc(session_id)}/diff`;
    return await this.transport.request<S['SessionDiffResponse']>('GET', path);
  }

  /**
   * Export Agent Session
   *
   * Export the complete session history.
   *
   * The complete, ordered history of the session (agent output, tool calls, thinking,
   * lifecycle events, sandbox output, message events) as an ordered
   * manifest of presigned segment URLs.
   *
   * Segments are gzip members: download in order and concatenate
   * for one file. The JSON API never carries the bytes (same
   * two-step as files). /records is the paged live view of the
   * same data.
   */
  async export(session_id: string): Promise<S['GetSessionLogResponse']> {
    const path = `/v1/sessions/${enc(session_id)}/export`;
    return await this.transport.request<S['GetSessionLogResponse']>('GET', path);
  }

  /**
   * Get Agent Session
   *
   * Return one session.
   *
   * The public wire shape — the same shape the stream's session
   * frames carry, with attributed_user and stopped_by_user resolved
   * at read time.
   *
   * The heavy near-static blobs (config snapshot, input/output)
   * live on the detail endpoints, not here.
   */
  async get(session_id: string): Promise<S['SessionResponse']> {
    const path = `/v1/sessions/${enc(session_id)}`;
    return await this.transport.request<S['SessionResponse']>('GET', path);
  }

  /**
   * Ingest Agent Session Transcript
   *
   * Append transcript lines to a session's record.
   *
   * The in-sandbox tailer for interactive sessions.
   *
   * A sandbox token may only push its own session's transcript.
   * Idempotent by transcript line uuid; tolerant of malformed lines.
   */
  async ingestTranscript(session_id: string, options: { lines: (string)[]; offset?: number }): Promise<S['TranscriptIngestResult']> {
    const path = `/v1/sessions/${enc(session_id)}/transcript`;
    const body = buildBody({ lines: options.lines, offset: options.offset });
    return await this.transport.request<S['TranscriptIngestResult']>('POST', path, { body });
  }

  /**
   * List Agent Sessions
   *
   * List cloud agent sessions, newest first.
   *
   * Optionally filtered by automation (id or name), source, time
   * window, attributed author, repository, and whether the session is
   * still going.
   */
  async list(options: { automation?: string | null; source?: (S['SessionSource'])[] | null; days?: number | null; start?: string | null; end?: string | null; limit?: number; cursor?: string | null; author_id?: number | null; repo?: string | null; unfinished?: boolean } = {}): Promise<Page<S['Session'], S['SessionsListResponse']>> {
    const path = '/v1/sessions';
    const query = buildQuery({ automation: options.automation, source: options.source, days: options.days, start: options.start, end: options.end, limit: options.limit, cursor: options.cursor, author_id: options.author_id, repo: options.repo, unfinished: options.unfinished });
    const response = await this.transport.request<S['SessionsListResponse']>('GET', path, { query });
    return new Page(response, 'sessions', (cursor) =>
      this.list({ ...options, cursor })
    );
  }

  /**
   * Get Agent Session Output
   *
   * Return the session's typed output.
   *
   * The payload the agent submitted through its config-declared
   * output.json_schema, as the raw JSON body with no envelope. 404
   * while the session is still running (poll GET /v1/sessions/{id}),
   * when the agent declares no output block, or when no execution
   * produced output.
   */
  async output(session_id: string): Promise<void> {
    const path = `/v1/sessions/${enc(session_id)}/output`;
    await this.transport.request<void>('GET', path);
  }

  /**
   * Get Agent Session Records
   *
   * Return the session's stored transcript records, oldest first.
   *
   * Pagination is opt-in (cursor/limit); a bare call returns the
   * full retained transcript. Available to sandbox tokens too: an
   * agent answering "did X look into Y?" needs to read the sessions
   * it finds, and any org member sees the same transcript in the
   * dashboard.
   */
  async records(session_id: string, options: { cursor?: string | null; limit?: number | null } = {}): Promise<Page<S['ClaudeSessionRecord'] | S['CodexSessionRecord'] | S['LifecycleSessionRecord'], S['SessionRecordsListResponse']>> {
    const path = `/v1/sessions/${enc(session_id)}/records`;
    const query = buildQuery({ cursor: options.cursor, limit: options.limit });
    const response = await this.transport.request<S['SessionRecordsListResponse']>('GET', path, { query });
    return new Page(response, 'records', (cursor) =>
      this.records(session_id, { ...options, cursor })
    );
  }

  /**
   * Send Agent Session Message
   *
   * Send a message to a session.
   *
   * 409 for react/cron, non-interactive, and closed sessions.
   * Returns the created message so the caller can track it by id; a
   * retried send with the same idempotency_key returns the original
   * message.
   */
  async sendMessage(session_id: string, options: { idempotency_key?: string | null; images?: (S['ImageAttachment'])[]; message: string }): Promise<S['SessionMessageResponse']> {
    const path = `/v1/sessions/${enc(session_id)}/messages`;
    const body = buildBody({ idempotency_key: options.idempotency_key, images: options.images, message: options.message });
    return await this.transport.request<S['SessionMessageResponse']>('POST', path, { body });
  }

  /**
   * Start Agent Session
   *
   * Start a cloud agent session.
   *
   * The daily driver: a prompt, optionally where to run it
   * (`environment`) and the run's own settings, in the AutomationConfig
   * vocabulary. What you send is what runs: omit `environment` and the
   * session runs in the built-in basic sandbox. A missing model or
   * budget comes from the organization's settings, so
   * `{"prompt": "..."}` alone is a complete request. `prompt` is the
   * first message; omit it and the session starts idle, waiting for
   * one. 400 when `interactive` is false and there is no prompt, or
   * when `budget` exceeds the organization's per-session ceiling. To
   * run a saved automation, use POST /v1/automations/{automation_id}/sessions.
   */
  async start(options: { budget?: number | null; claude?: S['ClaudeConfig'] | null; codex?: S['CodexConfig'] | null; environment?: string | S['EnvironmentConfig'] | null; force_rebuild?: boolean; images?: (S['ImageAttachment'])[]; interactive?: boolean; metadata?: Record<string, string>; output?: S['OutputConfig'] | null; permissions?: S['PermissionsConfig'] | null; prompt?: string | null; repositories?: (string)[] | null; skills?: (S['SkillRef'])[] | null } = {}): Promise<S['SessionResponse']> {
    const path = '/v1/sessions';
    const body = buildBody({ budget: options.budget, claude: options.claude, codex: options.codex, environment: options.environment, force_rebuild: options.force_rebuild, images: options.images, interactive: options.interactive, metadata: options.metadata, output: options.output, permissions: options.permissions, prompt: options.prompt, repositories: options.repositories, skills: options.skills });
    return await this.transport.request<S['SessionResponse']>('POST', path, { body });
  }

  /**
   * Stop Agent Session
   *
   * Stop an in-flight session and return it.
   *
   * stopped_by is recorded only when the caller's credential maps
   * to a GitHub account.
   */
  async stop(session_id: string): Promise<S['SessionResponse']> {
    const path = `/v1/sessions/${enc(session_id)}/stop`;
    return await this.transport.request<S['SessionResponse']>('POST', path);
  }

  // ---- lifecycle sugar (hand-written layer over the generated core) ----

  /** Start a session and return a handle over it. */
  async run(
    options: Parameters<EllipsisSessions['start']>[0]
  ): Promise<SessionHandle> {
    const response = await this.start(options);
    return new SessionHandle(this, response.session);
  }

  /** A handle over an existing session. */
  async handle(sessionId: string): Promise<SessionHandle> {
    const response = await this.get(sessionId);
    return new SessionHandle(this, response.session);
  }
}

class EllipsisSettingsOrganization {
  constructor(private readonly transport: Transport) {
  }

  /**
   * Get Organization Settings
   *
   * Get the organization settings.
   *
   * The default model every session falls back to when neither its
   * request nor its automation names one, and the per-session budget
   * ceiling no session may exceed.
   */
  async get(): Promise<S['OrganizationSettings']> {
    const path = '/v1/settings/organization';
    return await this.transport.request<S['OrganizationSettings']>('GET', path);
  }

  /**
   * Set Organization Settings
   *
   * Set the organization settings.
   *
   * Replaces both: `default_model` accepts an alias or canonical id
   * and is stored canonical; `budget_ceiling.session` is in US
   * dollars, at most the platform ceiling. Null clears each.
   * Refused for sandbox tokens (potentially prompt-injected code must
   * not repoint the organization's defaults).
   */
  async set(options: { budget_ceiling?: S['BudgetCeiling']; default_model?: string | null } = {}): Promise<S['OrganizationSettings']> {
    const path = '/v1/settings/organization';
    const body = buildBody({ budget_ceiling: options.budget_ceiling, default_model: options.default_model });
    return await this.transport.request<S['OrganizationSettings']>('PUT', path, { body });
  }
}

class EllipsisSettings {
  readonly organization: EllipsisSettingsOrganization;
  constructor(private readonly transport: Transport) {
    this.organization = new EllipsisSettingsOrganization(transport);
  }
}

class EllipsisTemplates {
  constructor(private readonly transport: Transport) {
  }

  /**
   * Get Agent Template
   *
   * Return one built-in agent template by slug.
   */
  async get(template_id: string): Promise<S['AgentTemplate']> {
    const path = `/v1/templates/${enc(template_id)}`;
    return await this.transport.request<S['AgentTemplate']>('GET', path);
  }

  /**
   * List Agent Templates
   *
   * List the built-in starter agent templates.
   *
   * Behind auth but not account-scoped — the data is static
   * product content shared by the dashboard, landing site, and CLI.
   */
  async list(): Promise<S['AgentTemplatesListResponse']> {
    const path = '/v1/templates';
    return await this.transport.request<S['AgentTemplatesListResponse']>('GET', path);
  }
}

export class Ellipsis {
  private readonly transport: Transport;
  readonly alerts: EllipsisAlerts;
  readonly analytics: EllipsisAnalytics;
  readonly auth: EllipsisAuth;
  readonly automations: EllipsisAutomations;
  readonly environments: EllipsisEnvironments;
  readonly files: EllipsisFiles;
  readonly integrations: EllipsisIntegrations;
  readonly memories: EllipsisMemories;
  readonly models: EllipsisModels;
  readonly reviews: EllipsisReviews;
  readonly secrets: EllipsisSecrets;
  readonly sessions: EllipsisSessions;
  readonly settings: EllipsisSettings;
  readonly templates: EllipsisTemplates;

  constructor(options: TransportOptions) {
    this.transport = new Transport(options);
    this.alerts = new EllipsisAlerts(this.transport);
    this.analytics = new EllipsisAnalytics(this.transport);
    this.auth = new EllipsisAuth(this.transport);
    this.automations = new EllipsisAutomations(this.transport);
    this.environments = new EllipsisEnvironments(this.transport);
    this.files = new EllipsisFiles(this.transport);
    this.integrations = new EllipsisIntegrations(this.transport);
    this.memories = new EllipsisMemories(this.transport);
    this.models = new EllipsisModels(this.transport);
    this.reviews = new EllipsisReviews(this.transport);
    this.secrets = new EllipsisSecrets(this.transport);
    this.sessions = new EllipsisSessions(this.transport);
    this.settings = new EllipsisSettings(this.transport);
    this.templates = new EllipsisTemplates(this.transport);
  }

  /**
   * Get Budget
   *
   * Return the caller's current budget summary.
   */
  async budget(): Promise<S['BudgetSummary']> {
    const path = '/v1/budget';
    return await this.transport.request<S['BudgetSummary']>('GET', path);
  }

  /**
   * Current Identity
   *
   * Return the identity behind the caller's credential.
   */
  async me(): Promise<S['WhoAmIResponse']> {
    const path = '/v1/me';
    return await this.transport.request<S['WhoAmIResponse']>('GET', path);
  }

  /**
   * Get Usage
   *
   * Return the caller's usage dashboard data.
   */
  async usage(): Promise<S['GetUsageDashboardResponse']> {
    const path = '/v1/usage';
    return await this.transport.request<S['GetUsageDashboardResponse']>('GET', path);
  }
}
